CREATE TABLE "User" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "Username" VARCHAR(255) NOT NULL UNIQUE,
    "Email" VARCHAR(255) NOT NULL UNIQUE,
    "Password" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE "Task" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "Title" VARCHAR(255) NOT NULL,
    "Description" TEXT,
    "DueDate" TIMESTAMP,
    "Status" VARCHAR(20) NOT NULL,
    "Priority" VARCHAR(20) NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UserId" UUID NOT NULL,
  CONSTRAINT fk_UserId FOREIGN KEY ("UserId") References "User"("Id") ON DELETE CASCADE
);


CREATE TABLE "Token" (
  "Token" TEXT PRIMARY KEY,
  "UserId" UUID NOT NULL,
  "ExpireAt" TIMESTAMP NOT NULL,
  CONSTRAINT fk_UserId FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
