@LunaTestTask_HostAddress = http://localhost:5096

### Get all tasks
GET {{LunaTestTask_HostAddress}}/tasks
Accept: application/json

### Get all tasks
GET {{LunaTestTask_HostAddress}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5YmY1NmM0LTUwN2UtNGNmZi04OTY1LWQ3MjhmMDk4NTZmMSIsInVuaXF1ZV9uYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwibmJmIjoxNzMzMTY3MjE4LCJleHAiOjE3MzU3NTkyMTgsImlhdCI6MTczMzE2NzIxOH0.uAza0ADdSfYobIoj9aTYqe73yuOseVOFCTV-pO_G4gA
Accept: application/json


### Get specific task
@id = ceb54f42-0b5f-498e-8730-3b00a17d6614

GET {{LunaTestTask_HostAddress}}/tasks/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5YmY1NmM0LTUwN2UtNGNmZi04OTY1LWQ3MjhmMDk4NTZmMSIsInVuaXF1ZV9uYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwibmJmIjoxNzMzMTY3MjE4LCJleHAiOjE3MzU3NTkyMTgsImlhdCI6MTczMzE2NzIxOH0.uAza0ADdSfYobIoj9aTYqe73yuOseVOFCTV-pO_G4gA
Accept: application/json
### Create new task

POST {{LunaTestTask_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "New test one",
  "dueDate": "2024-12-05T10:00:00Z",
  "status": "InProgress",
  "priority": "Low"
}

### Create new user
POST {{LunaTestTask_HostAddress}}/users/register
Content-Type: application/json

{
  "Username": "TestUser",
  "Email": "test@email.com",
  "Password": "TestPassword&7"
}

### Login user
POST {{LunaTestTask_HostAddress}}/users/login
Content-Type: application/json

{
  "Username": "TestUser",
  "Email": "test@email.com",
  "Password": "TestPassword&7"
}
